### ISSUE TITLE
Error on install of server

### ISSUE THREAD

**Issue by bmpreston** [jaylagorio/Nightscout-on-Windows-Server#3]
Please see the attached debug log.  Installing on Windows 10 Professional sitting on a VM on QNAP.  As I run the npm install command, I initially found it was lacking sdk 8.1, which I found, downloaded and installed.  Now I'm seeing an acorn command.  

Any help on this issue?

[2020-05-18T03_05_04_073Z-debug.log](https://github.com/jaylagorio/Nightscout-on-Windows-Server/files/4641808/2020-05-18T03_05_04_073Z-debug.log)

**Comment by jaylagorio** [comment]
Did you install Microsoft Visual Studio 2015? Please see this issue: https://github.com/nightscout/cgm-remote-monitor/issues/4843

https://my.visualstudio.com/Downloads?q=Visual%20Studio%20Express%202015%20for%20Windows%20Desktop

**Comment by bmpreston** [comment]
I have it as installed.  I will uninstall and reinstall now, updates shortly.

Thank you for responding!

**Comment by bmpreston** [comment]
Duplicate of #4843.  This does seem to be my issue.  I am reinstalling VS Express 2015 to attempt correction.

**Comment by jaylagorio** [comment]
I'm sorry it took me so long, I was doing a rebuild of my primary machine and wanted to confirm the possible duplication. I'm glad to see it's working, let me know if I can help with anything more!

**Comment by bmpreston** [comment]
This didn't actually fix it.  I'm pretty much giving up.  The amount of the install is not for the faint of heart to install all the databases, the VS (which seems to be the problem), etc.  I host a lot of databases on my VM and this one is just not friendly at all.

Thank you for all the time you have put into this.  Amazing to have something as cool as Nightscout, even if Windows is just not designed for it.

**Comment by jaylagorio** [comment]
Are you using a VM host? I would need some time, but it would be pretty easy for me to bring up a new Hyper-V VM that I could export and have you import into your environment. I also don't know which Windows version/client/server you're using, if you want to set up a video call I can help walk you through all that stuff.

**Comment by bmpreston** [comment]
I’m using Windows 10 hosted on a QNAP server.
