### ISSUE TITLE
HTTPS/SSL Problems

### ISSUE THREAD

**Issue by cO5Mo2** [jaylagorio/Nightscout-on-Windows-Server#5]
Hi Jay and first of all thank you for this walkthrough! Very detailed step-by-step explaination that helped me a lot!

My problem just surfaced after using AndroidAPS. I did not have any problems with xDrip or any web browser. Long story short, I think I can't get HTTPS working properly on port 443.

-When I access https://localhost I get the following error message:
SSL_ERROR_RX_RECORD_TOO_LONG

-In AndroidAPS I get the following error from Nightscout-Client:
ERROR io.socket.engineio.client.EngingeIOException: xhr poll error

Searching the web it looks like it's an authorization/SSL problem. But I have no clue on how to fix that. Here is my setup:

-Windows 10 Pro Server with latest updates
-Installed everything exactly as you wrote:
  -Visual Studio Express 2015 for Windows Desktop
  -MongoDB 4.0.0 for Windows Server 2008 R2 and later,
  -Python 2.7.11
  -Git for Windows 2.18.0
  -Node.js 10.15.2 x64

I can't really set up a reverse proxy on the machien as you described, because I own a Synology NAS which acts as my reverse proxy for my subdomains. So I set up my nightscout subdomian there. 

As a workaround I set the port to 80, my reverse proxy forwaded https to the loca https. It works for web browsers and xdrip with the URL https://nightscout.mydomain.com but not for AAPS.

Any idea what could have gone wrong? Thank you in advance!

**Comment by jaylagorio** [comment]
Good evening, cO5Mo2,

When you have AndroidAPS connected to the same network segment as the Nightscout server do you still get the error? Have you tried setting a Let's Encrypt certificate up for the Nightscout server? You might check with the AndroidAPS crew like @MilosKozak to get better information about what specifically about the AndroidAPS SSL error indicates.

Let me know!

**Comment by cO5Mo2** [comment]
Thank you for your quick answer and sorry for my late response.

The problem is that https doesnt work at all, even in the local network. So if I try to connect to https://localhost in Firefox, I get error code SSL_ERROR_RX_RECORD_TOO_LONG.

I set an Let's Encrypt certificate for my NAS, which is in the same LAN as my Nightscout server and forwards http and https to Nightscout. 

My workaround as described above works great for all browsers and xdrip, but not for AndroidAPS. I asked on the Facebook group, but couldn't solve it.

For https to work, do I need to set up a certificate in Nightscout or node.js directly? How would I do that?

Thanks a lot for your help!

**Comment by jaylagorio** [comment]
So I think at this point I don't have the knowledge of how AndroidAPS works under the hood nor do I have a device to test with to try to figure out why it's not working. Since the web browser and xdrip are working fine I can't confidently say it's your Nightscout instance that's the problem. I think filing an issue with the AndroidAPS folks is probably your best way to go. I'm sorry I can't be of more help!
