### ISSUE TITLE
additional steps needed for androidaps

### ISSUE THREAD

**Issue by sdolenc** [jaylagorio/Nightscout-on-Windows-Server#6]
Thank you for your tutorial. It saved me a ton of time! I noticed there were some additional steps that androidaps requires
1. adding websockets to the reverse poxy. I learned about this from: https://github.com/nightscout/AndroidAPS/issues/2063#issuecomment-1242760982 and solved it for iis using this [tutorial](https://www.oxygenxml.com/doc/versions/24.1.0/ug-waCustom/topics/WA-websocket.html#:~:text=How%20to%20Enable%20WebSocket%20Support%20When%20Using%20IIS,Role%20and%20Features%20wizard%20and%20select%20Server%20Roles)
2. free https over IIS using let's encrypt. I used a couple tutorials like [this one](https://www.snel.com/support/how-to-install-lets-encrypt-with-iis-on-windows-server-2019/)

**Comment by sdolenc** [comment]
i just noticed that the web.config in nightscout's root probably takes care of "1" already and adding info about "2" is optional. Feel free to close this issue

**Comment by jaylagorio** [comment]
@sdolenc Glad to hear this saved you time! I haven't had problems with websockets before and that's probably because of the web.config like you said. I think Let's Encrypt is out of scope for the time being but I'll consider adding it during the next revision. Thanks for your comments!

**Comment by LoopLuke100** [comment]
Hello @sdolenc - can you help me with point 3 in the tutorial of IIS? I did points 1 and 2 but don't understand where to look for point 3 :( 
I'm having the issue with xhr poll error for quite a long time.

**Comment by sdolenc** [comment]
@LoopLuke100 , I uploaded this video - hope it helps solve this for you. https://www.youtube.com/watch?v=AC0YYU94xYc

I can't remember if I had to do other stuff offhand. I set this up so long ago
